version: "3.8"

services:

  pokemon-service:
    build:
      context: ./pokemon-service
    container_name: pokemon-service
    depends_on:
      - pokemon-db
    environment:
      PORT: 3010
      POSTGRES_DB: pokemon_db
      POSTGRES_USER: pokemon_user
      POSTGRES_PASSWORD: pokemon_pass
      PGPORT: 5432
      POSTGRES_HOST: pokemon-db
    ports:
      - "3010:3010"
    volumes:
      - ./pokemon-service:/app
    command: [ "npm", "run", "dev" ]

  pokemon-db:
    build:
      context: ./pokemon-db
    container_name: pokemon-db
    environment:
      POSTGRES_USER: pokemon_user
      POSTGRES_PASSWORD: pokemon_pass
      POSTGRES_DB: pokemon_db
    ports:
      - "3011:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  pokemon-db-seeder:
    build:
      context: ./pokemon-db-seeder
    container_name: pokemon-db-seeder
    depends_on:
      - pokemon-db
    environment:
      DB_HOST: pokemon-db
      DB_DATABASE: pokemon_db
      DB_USER: pokemon_user
      DB_PASSWORD: pokemon_pass

  pokemon-viewer:
    build:
      context: ./pokemon-viewer
      args:
        VITE_API_URL: "http://localhost:3010/api"
    container_name: pokemon-viewer
    ports:
      - "5173:3000"


volumes:
  pgdata:
